config/routes.rb
Rails.application.routes.draw do

  namespace :api, { format: 'json' }   do
    resources :tasks, only: [:update]
    get 'tasks/calendar' => 'tasks#calendar'
    get 'tasks/mail' => 'tasks#mail'
  end

  root 'tasks#index'
  resources :tasks, except: [:index]
  get '/my_tasks' => 'tasks#index'
  resources :users, except: [:index, :destroy]
  put '/users/done_osekkyo/:id' => 'users#done_osekkyo'
  patch '/users/done_osekkyo/:id' => 'users#done_osekkyo'
  get '/users/:id/check_oko' => 'users#check_oko'
  get '/calendar' => 'tasks#calendar'
  resources :groups, except: [:index, :destroy] do
    resources :tasks, except: [:index] do
      collection do
        get '/' => 'tasks#index_group'
      end
    end
    resources :group_users, only: [:destroy, :show]
  end

  namespace :admin do
    root 'tasks#index'
    resources :tasks, except: [:index]
    get '/calendar' => 'tasks#calendar'
    get '/my_tasks' => 'tasks#index'
    resources :users, :labels
    resources :groups do
      resources :tasks, except: [:index] do
        collection do
          get '/' => 'tasks#index_group'
        end
      end
      resources :group_users, only: [:destroy, :show]
    end
  end

  get 'login', to: 'sessions#new'
  post 'login' => 'sessions#create'
  get 'sessions/destroy'
  get '/ayame' => 'ayame#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_tasks, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :tasks, through: :group_tasks
  has_many :users, through: :group_users
  accepts_nested_attributes_for :group_tasks
  accepts_nested_attributes_for :group_users
  validate :validate_name_error

  def validate_name_error
    if name.empty?
      errors.add(:name, "グループ名を入力してください")
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :task_labels, dependent: :destroy
  has_many :labels, through: :task_labels
  has_many :group_tasks, dependent: :destroy
  has_many :groups, through: :group_tasks
  belongs_to :holder, class_name: 'User', foreign_key: 'user_id'
  belongs_to :user
  belongs_to :charge_user, class_name: 'User'
  # after_save :create_labels
  # before_update :create_labels
  after_create :create_labels

  validate :validate_caption_error, :check_caption_empty

  enum priority:{
      high: 0,
      middle: 1,
      low: 2
  }

  enum status:{
      done: 0,
      doing: 1,
      to_do: 2
  }

  # scope :get_by_caption, ->(caption) {
  #   where("caption like ?", "%#{caption}%")
  # }

  # 三種類全部作っとく
  scope :get_by_status, ->(status) {
    where(status: status)
  }

  # enum の gem　がある
  scope :status_to_do, -> {
    where(status: 2)
  }

  scope :status_doing, -> {
    where(status: 1)
  }

  scope :status_done, -> {
    where(status: 0)
  }

  scope :not_status_done, -> {
    where.not(status: 0)
  }

  def validate_caption_error
    if caption.length > 100
      errors.add(:caption, "が100文字を超えている")
    end
  end

  def check_caption_empty
    if caption.empty?
      errors.add(:caption, "ない")
    end
  end


  def create_labels
    self.task_labels.each do |label|
      Label.where(id: label.label_id).destroy_all
    end
    label.gsub(/(\s|　)+/, ' ').split(" ").each do | label_name |
      label_id = Label.find_or_create_by(name: label_name)
      self.task_labels.find_or_create_by(label: label_id)
    end
  end

  def link_group

  end

end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < ApplicationController
  layout 'admin_tasks'

  before_action :user_logged_in?, :admin_user?

  helper_method :sort_column, :sort_direction

  def index
    @task = Task.new
    @user = current_user
    @group = Group.new
    tasks_by_status(current_user.id, "my_tasks")
  end

  def index_group
    check_join_group
    @task = Task.new
    @user = current_user
    @group = Group.new
    @group_tasks = Group.find(params[:group_id])
    tasks_by_status(@group_tasks.tasks.ids, "group")
  end


  def new
    @task = Task.new
  end

  def create
    @task = Task.new(create_params)
    @user = current_user
    group = Group.find(params[:group_id])
    @task.user_id = current_user.id
    if @task.save
      group.group_tasks.create(task: @task)
      flash[:notice] = "タスクが追加されました"
    else
      render json: { messages: @task.errors.full_messages }, status: :bad_request
    end
  end

  def edit
    @task = find_task_by_id
  end

  def update
    @task = find_task_by_id
    if @task.update(create_params)
      flash[:notice] = "タスクが編集されました"
    else
      render json: { messages: @task.errors.full_messages }, status: :bad_request
    end
  end

  def show
    @task = find_task_by_id
  end

  def destroy
    @task = find_task_by_id
    @task.destroy
    flash[:notice] = "タスクが削除されました"
    redirect_back(fallback_location: root_path)
  end

  def calendar
    @user = current_user
    @group = Group.new
    group_tasks = Group.select("id").find(@user.groups.ids)
    @tasks = []
    group_tasks.each{ |group_task|
      @tasks << (Task.all.where(id: group_task.tasks.ids).not_status_done)
    }
  end

  private
  # task_ids?, tasksを引数として渡す
  def tasks_by_status(task_ids, index_name)
    if index_name == "my_tasks"
      # tasks決定が重複しているのはNG
      tasks = Task.where(user_id: task_ids).not_status_done
      @task_status_done_count = Task.where(user_id: task_ids).status_done.size
    else
      tasks = Task.where(id: task_ids).not_status_done
      @task_status_done_count = Task.where(id: task_ids).status_done.size
    end
    time_now = Time.now - (Time.now.hour * 60 * 60 + Time.now.min * 60 + Time.now.sec)
    @task_blue_count = tasks.where("deadline > '#{time_now + 3.day}'").size
    @task_yellow_count = tasks.where(deadline: (time_now)..(3.days.since)).size
    @task_red_count = tasks.where("deadline < '#{time_now}'").size
    if index_name == "group"
      tasks = Task.where(id: task_ids).order(sort_column + ' ' + sort_direction)
    else
      tasks = Task.where(charge_user_id: task_ids)
    end
    @tasks_to_do = tasks.status_to_do
    @tasks_doing = tasks.status_doing
    @tasks_done = tasks.status_done
  end

  def create_params
    params.require(:task).permit(:id, :caption, :priority, :deadline, :status, :label, :created_at, :user_id, :charge_user_id, :group_ids)
  end

  def find_task_by_id
    Task.find(params[:id])
  end

  def check_join_group
    return if current_user.admin
    user = current_user
    if user.groups.where(id: params[:group_id]).empty?
      redirect_to admin_root_path
    end
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end

  def sort_column
    Task.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end
end

app/controllers/api/tasks_controller.rb
class Api::TasksController < ApplicationController
  def index
  end

  def calendar
    @user = current_user
    group_tasks = Group.find(@user.groups.ids)
    @tasks = []
    from = Time.local(params[:calendar][:year], params[:calendar][:month])
    to   = from + 1.month
    group_tasks.each do |group_task|
      tasks = group_task.tasks.not_status_done
      tasks.where(deadline: from...to).order(deadline: :desc).each do |task|
        user_image = "/assets/images/users"
        if task.charge_user.image_name == "default_user.png"
          user_image = "#{user_image}/#{task.charge_user.image_name}"
        else
          user_image = "#{user_image}/#{task.charge_user.id}/#{task.charge_user.image_name}"
        end
        @tasks.push(group:group_task.name, caption: task.caption, charge_user: task.charge_user.name, deadline: task.deadline, user_image: user_image, charge_user_id: task.charge_user.id, task_id: task.id)
      end
    end
    render 'calendar', formats: 'json', handlers: 'jbuilder'
  end

  def mail
    from_user = current_user
    to_user = User.find(params[:mail][:user_id])
    to_user.oko = true
    to_user.save
    task = Task.find(params[:mail][:task_id])
    RelationshipMailer.oko_notification(from_user, to_user, task).deliver
  end

  def show

  end

  def update
    if params[:task][:id].present? or params[:task][:status].present?
      task = Task.find(params[:task][:id])
      if task.update(create_params)

      end
    end
  end

  private
  def create_params
    params.require(:task).permit(:id, :status)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  layout "tasks"

  before_action :user_logged_in?

  helper_method :sort_column, :sort_direction

  def index
    @task = Task.new
    @user = current_user
    @group = Group.new
    tasks(current_user.id, "my_tasks")
  end

  def index_group
    check_join_group
    @task = Task.new
    @user = current_user
    @group = Group.new
    @group_tasks = Group.find(params[:group_id])
    tasks(@group_tasks.tasks.ids, "group")
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(create_params)
    @user = current_user
    group = Group.find(params[:group_id])
    @task.user_id = current_user.id
    if @task.save!
      group.group_tasks.create(task: @task)
      flash[:notice] = "タスクが追加されました"
    else
      render json: { messages: @task.errors.full_messages }, status: :bad_request
    end
  end

  def edit
    @task = find_task_by_id
  end

  def update
    @task = find_task_by_id
    if @task.update(create_params)
      flash[:notice] = "タスクを更新"
    else
      render json: { messages: @task.errors.full_messages }, status: :bad_request
    end
  end

  def show
    @task = find_task_by_id
  end

  def destroy
    @task = find_task_by_id
    @task.destroy
    flash[:notice] = "タスクを削除しました"
    # redirect_to tasks_path
    redirect_back(fallback_location: root_path)
  end

  def calendar
    @user = current_user
    @group = Group.new
    group_tasks = Group.select("id").find(@user.groups.ids)
    @tasks = []
    group_tasks.each{ |group_task|
      @tasks << (Task.all.where(id: group_task.tasks.ids).not_status_done)
    }
  end

  private
  def tasks(task_ids, index_name)
    if index_name == "my_tasks"
      tasks = Task.all.where(user_id: task_ids).not_status_done
      @task_status_done_count = Task.all.where(user_id: task_ids).status_done.size
    else
      tasks = Task.all.where(id: task_ids).not_status_done
      @task_status_done_count = Task.all.where(id: task_ids).status_done.size
    end
    time_now = Time.now - (Time.now.hour * 60 * 60 + Time.now.min * 60 + Time.now.sec)
    @task_blue_count = tasks.where("deadline > '#{time_now + 3.day}'").size
    @task_yellow_count = tasks.where(deadline: (time_now)..(3.days.since)).size
    @task_red_count = tasks.where("deadline < '#{time_now}'").size
    if index_name == "group"
      tasks = Task.all.where(id: task_ids).order(sort_column + ' ' + sort_direction)
    else
      tasks = Task.all.where(charge_user_id: task_ids)
    end
    @tasks_to_do = tasks.status_to_do
    @tasks_doing = tasks.status_doing
    @tasks_done = tasks.status_done
  end

  def create_params
    params.require(:task).permit(:id, :caption, :priority, :deadline, :status, :label, :created_at, :user_id, :group_id, :charge_user_id)
  end

  def find_task_by_id
    Task.find(params[:id])
  end

  def check_join_group
    return if current_user.admin
    user = current_user
    if user.groups.where(id: params[:group_id]).empty?
      redirect_to root_path
    end
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def sort_column
    Task.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end
end

app/helpers/admin/tasks_helper.rb
module Admin::TasksHelper
end

app/helpers/api/tasks_helper.rb
module Api::TasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_edit_modal.html.slim
div class="modal fade" id="edit_button_#{task.id}" role="dialog"
  div.modal-dialog
    div.modal-content
      div.modal-header
        button type="button" class="close" data-dismiss="modal"
        h4 class="modal-title" 編集
      div.modal-body
        = render partial: 'form_task', locals: {task: task, submit_text: t("task.edit")}

app/views/tasks/_form_serch.html.slim
= form_for(tasks_path, method: "get") do
  = label_tag :name, t("ttributes.caption"), class: "control-label huchidori_font"
  = text_field_tag :caption, params[:caption], class: "form-control"
  = label_tag :name, "状態", class: "control-label huchidori_font"
  = select_tag :status, options_for_select(Task.statuses.map { |k, _v| [t("status.#{k}"), k] }), include_blank: true, class: "form-control"
  = submit_tag "検索", class: "btn"

app/views/tasks/_form_task.html.slim
= form_for task, html: { class: "data-form" }, remote: true  do |f|
  div.form-group
    = f.label :"#{t("ttributes.caption")}: ", class: "control-label huchidori_font"
    = f.text_field :caption, class: "form-control"
  div.form-group
    = f.label :"優先度: ", class: "control-label huchidori_font"
    = f.select :priority, Task.priorities.map { |k, _v| [t("priority.#{k}"), k] }, {}, class: "form-control"
  div.form-group
    = f.label :"締め切り: ", class: "control-label huchidori_font"
    = f.date_select :deadline, {}, class: "form-control"
  div.from-group
    = f.label :"状態: ", class: "control-label huchidori_font"
    = f.select :status, Task.statuses.map {|k, _v| [t("status.#{k}"), k]}, {}, class: "form-control", id: "new_task_status", disabled: true
  - if controller.action_name.include?("group")
    div.form-group
      = f.label :"担当者:　 ", class: "control-label huchidori_font"
      = f.select :charge_user_id, options_from_collection_for_select(@group_tasks.users, :id, :name, { selected: @group_tasks.users.find(task.charge_user.id).id }), {}, { class: "user_select_edit_#{task.id} selectpicker "}
      img.user_icon3 id="jquery_change_user_icon_#{task.id}" height="80px" src = ""
  div.form-group
    = f.label :"付箋: ", class: "control-label huchidori_font"
    = f.text_field :label, class: "form-control"
  div.form-group
    div id="submit_button" class="btn btn-primary data-submit" #{submit_text}

app/views/tasks/_form_task_new.html.slim
= form_for [@group_tasks, task], html: { class: "data-form" }, remote: true do |f|
  div.form-group
    = f.label :"#{t("ttributes.caption")}: ", class: "control-label huchidori_font"
    = f.text_field :caption, class: "form-control"
  div.form-group
    = f.label :"優先度: ", class: "control-label huchidori_font"
    = f.select :priority, Task.priorities.map { |k, _v| [t("priority.#{k}"), k] }, {}, class: "form-control"
  div.form-group
    = f.label :"締め切り: ", class: "control-label huchidori_font"
    = f.date_select :deadline, {}, class: "form-control"
  div.from-group
    = f.label :"状態: ", class: "control-label huchidori_font"
    = f.select :status, Task.statuses.map {|k, _v| [t("status.#{k}"), k]}, {}, class: "form-control", id: "new_task_status", disabled: true
  div.form-group
    = f.label :"担当者:　 ", class: "control-label huchidori_font"
    = f.select :charge_user_id, options_from_collection_for_select(@group_tasks.users, :id, :name, {selected: @group_tasks.users.find(session[:user_id]).id}), {}, { class: "user_select selectpicker "}
    img.modal_user_icon.user_icon3 height="80px" src = ""
  div.form-group
    = f.label :"付箋: ", class: "control-label huchidori_font"
    = f.text_field :label, class: "form-control"
  div.form-group
    div id="submit_button" class="btn btn-primary data-submit" #{submit_text}
    / input type="submit" id="submit_button" class="btn btn-primary data-submit"  #{submit_text}

app/views/tasks/_group_delete_user_modal.html.slim
div class="modal fade" id="edit_group_delete_member_modal" role="dialog"
  div.modal-dialog
    div.modal-content
      div.modal-header
        button type="button" class="close" data-dismiss="modal"
        h4 class="modal-title huchidori_font" メンバーを削除
      div.modal-body
        = form_for [group_tasks], html: { class: "data-form-group" }, remote: true do |f|
        div.form-group
          = label_tag "メンバー:　 "
          = select_tag "group[user_ids]", options_from_collection_for_select(User.all.where(id: group_tasks.users), :id, :name), include_blank: true, class: "select2 data_selected_group_user_delete"
        / = f.collection_select :user_id, class: "form-control"
        div.form-group
          div class="btn btn-info data-submit-group-delete" メンバーを削除

app/views/tasks/_group_edit_modal.html.slim
div class="modal fade" id="edit_group_member_modal" role="dialog"
  div.modal-dialog
    div.modal-content
      div.modal-header
        button type="button" class="close" data-dismiss="modal"
        h4 class="modal-title huchidori_font" メンバーを追加
      div.modal-body
        = form_for [group_tasks], html: { class: "data-form-group" }, remote: true do |f|
        div.form-group
          = label_tag "メンバー:　 "
          = select_tag "group[user_ids]", options_from_collection_for_select(User.all.where.not(id: group_tasks.users), :id, :name), include_blank: true, class: "data_selected_group_user select2"
        / = f.collection_select :user_id, class: "form-control"
        div.form-group
          div class="btn btn-info data-submit-group" メンバーを追加

app/views/tasks/_show.html.slim
/ = tasks
/ table align="right" class="table-bordered table-hover table-striped task"
thead
  tr
    th.text-center colspan="#{tasks.labels.size}" 詳細
  tbody
    tr
      td colspan="#{tasks.labels.size}" 優先度
    tr
      td.text-center colspan="#{tasks.labels.size}" = t("priority.#{tasks.priority}")
    tr
      td colspan="#{tasks.labels.size}" 締め切り
    tr
      td.text-center colspan="#{tasks.labels.size}" = tasks.deadline.to_s(:published_on)
    tr
      td colspan="#{tasks.labels.size}" 担当者
    tr
      td.text-center colspan="#{tasks.labels.size}" = tasks.charge_user.name
    tr
      td colspan="#{tasks.labels.size}" 作成者
    tr
      td.text-center colspan="#{tasks.labels.size}" = tasks.holder.name
    tr
      td colspan="#{tasks.labels.size}" 付せん
    tr
      - tasks.labels.each do |label|
        td.text-center
          div.label_border
            = label.name

app/views/tasks/_table_tasks_body.html.slim
- tasks.each do |task|
  - image_path = "/assets/images/users/"
  - if task.status != 'done'
    tr.jquery-ui-draggable data-task-id="#{task.id}" data-task-status="#{task.status}" data-task-caption="#{task.caption}" data-task-label="#{task.label}" data-task-user="#{task.user.name}" data-task-charge-user="#{task.charge_user.name}" id="#{task.id}"
      td.text-right
        - if task.charge_user.image_name == "default_user.png"
          img.user_icon width="80%" src = "#{image_path}#{task.charge_user.image_name}"
        - else
          img.user_icon width="80%" src = "#{image_path}#{task.charge_user.id}/#{task.charge_user.image_name}"
      - if Date.new(task.deadline.year, task.deadline.month, task.deadline.day)  < Date.today
        td.text-center class="task_caption_width_red task_caption_font" = link_to task.caption, task_path(task), remote: true
      - elsif Date.new(task.deadline.year, task.deadline.month, task.deadline.day)  < Date.today + 3.day
        td.text-center class="task_caption_width_yellow task_caption_font" = link_to task.caption, task_path(task), remote: true
      - else
        td.text-center class="task_caption_width task_caption_font" = link_to task.caption, task_path(task), remote: true
      td
        div type="button" class="btn" class="glyphicon glyphicon-pencil" data-toggle="modal" data-target="#edit_button_#{task.id}"
        = render partial: 'edit_modal', locals: { task: task }
        = link_to '', task_path(task.id), class: 'btn delete-task-btn glyphicon glyphicon-trash'  ,method: :delete, id: "delete_button", data: { title: t("confirm.title"), confirm: t("confirm.confirm") , cancel: t("confirm.cancel"), commit: t("confirm.commit")}
  - else
    tr.jquery-ui-draggable data-task-id="#{task.id}" data-task-status="#{task.status}" data-task-caption="#{task.caption}" data-task-label="#{task.label}" data-task-user="#{task.user.name}" data-task-charge-user="#{task.charge_user.name}" id="#{task.id}"
      td.text-right
        - if task.charge_user.image_name == "default_user.png"
          img.user_icon width="80%" src = "#{image_path}#{task.charge_user.image_name}"
        - else
          img.user_icon width="80%" src = "#{image_path}#{task.charge_user.id}/#{task.charge_user.image_name}"
      td.text-center class="task_caption_width_green task_caption_font" = link_to task.caption, task_path(task), remote: true
      td
        div type="button" class="btn" class="glyphicon glyphicon-pencil" data-toggle="modal" data-target="#edit_button_#{task.id}"
        = render partial: 'edit_modal', locals: {task: task}
        = link_to '', task_path(task.id), class: 'btn delete-task-btn glyphicon glyphicon-trash', method: :delete, id: "delete_button", data: {title: t("confirm.title"), confirm: t("confirm.confirm"), cancel: t("confirm.cancel"), commit: t("confirm.commit")}

app/views/tasks/_tasks_status.html.slim
span.text-muted
  img.user_icon width="30px" src = "/assets/images/system/postit_blue.png" まだ大丈夫：
  = @task_blue_count
span.text-muted
  img.user_icon width="30px" src = "/assets/images/system/postit_yellow.png" 期限三日以内：
  = @task_yellow_count
span.text-muted
  img.user_icon width="30px" src = "/assets/images/system/postit_red.png" 期限切れ：
  = @task_red_count
span.text-muted
  img.user_icon width="30px" src = "/assets/images/system/postit_green.png" 完了：
  = @task_status_done_count

app/views/tasks/calendar.html.slim
div.col-md-12 id="app"
  div id="calendar-nav"
    i.glyphicon.glyphicon-menu-left @click="moveLastMonth"
    span
      |
        {{calData.year}} - {{getMonthName(calData.month)}}
    i.glyphicon.glyphicon-menu-right @click="moveNextMonth"
  .col-md-6.calendar

    table.table id="calendar"
      thead
        tr
          th v-for="week in weekDays" {{week}}
      tbody
        tr v-for="week in calendar"
          td v-for="day in week" v-on:click="showTask(day.day)"
            template v-if="deadlineTasksDays.indexOf(day.day) == -1"
              | {{day.day}}
            template v-else=true
              | {{day.day}}<sup>{{dayCounts[day.day]}}</sup>
  .col-md-6
    div.text-center.deadline_task_p v-if="taskDates.length != 0"
      | {{dateDay}}日に期限が切れるタスク
    table.calendar_task.col-md-4 height="340px" v-for="task in taskDates"
      thead
      tbody
        tr
          td
            span.vue_group_title
              | {{task.group}}
        tr
          td
            .vue_caption_img
              .vue_caption_mask
                span.vue_caption_text
                  strong
                    | {{task.caption}}
        tr
          td.text-center
            img.user_icon height="70px" v-bind:src="task.userImage"
        tr
          td.text-center
            | {{task.chargeUser}}
        tr
          td.text-center
            template v-if="task.redTask"
              div.btn v-on:click="mailNotification(task.chargeUserId, task.taskId)"
                img.oko_icon height="50px" src="/assets/images/system/sd_ayame_oko_icon.png"

app/views/tasks/edit.html.slim
div class="container"
  - if @task.errors.any?
    div id = "error_explanation"
      - @task.errors.full_messages.each do |msg|
        javascript:
          toastr.error('#{msg}');

  h1 編集

  = form_for @task, :url => { action: 'update' }  do |f|
    div.form-group
      = f.label :"#{t("ttributes.caption")}: ", class: "control-label"
      = f.text_field :caption, class: "form-control"
    div.form-group
      = f.label :"優先度: ", class: "control-label"
      = f.select :priority, Task.priorities.map { |k, _v| [t("priority.#{k}"), k] }, {}, class: "form-control"
    div.form-group
      = f.label :"締め切り: ", class: "control-label"
      = f.date_select :deadline, {}, class: "form-control"
    div.form-group
      = f.label :"状態: ", class: "control-label"
      = f.select :status, Task.statuses.map { |k, _v| [t("status.#{k}"), k] }, {}, class: "form-control"
    div.form-group
      = f.label :"付箋: ", class: "control-label"
      = f.text_field :label, class: "form-control"
    h5
    = f.submit "お仕事♡を更新", class: "btn"

app/views/tasks/index.html.slim
.tasks_summary.col-xs-12
  table.col-xs-3
    tbody
      th.text-center.group_title 自分のタスク
  div.col-xs-5.col-sm-offset-4
    h5
      = render partial: 'tasks/tasks_status'

.tasks id="jquery-ui-draggable-connectToSortable"
  div.jquery-ui-draggable-drop
    table class="task waku_image_task jquery_ui_status" data-status="to_do"
      thead
        tr
          th.text-center class="task_bord_title table_title_font" colspan="2" 着手待ち
          th.text-left class="table_title"
      tbody.jquery-ui-sortable id="jquery_ui_to_do"
        tr
          th.text-center
          th.text-center
        = render partial: 'tasks/table_tasks_body', locals: { tasks: @tasks_to_do }
  div.jquery-ui-draggable-drop
    table class="task waku_image_task jquery_ui_status" data-status="doing"
      thead
        tr
          th.text-center class="task_bord_title table_title_font" colspan="2" 着手中
          th.text-left class="table_title"
      tbody.jquery-ui-sortable id="jquery_ui_doing"
        tr
          th.text-center
          th.text-center
        = render partial: 'tasks/table_tasks_body', locals: { tasks: @tasks_doing }
  div.jquery-ui-draggable-drop
    table class="task waku_image_task jquery_ui_status" data-status="done"
      thead
        tr
          th.text-center class="task_bord_title table_title_font" colspan="2" 完了
          th.text-left class="table_title"
      tbody.jquery-ui-sortable id="jquery_ui_done"
        tr
          th.text-center
          th.text-center
        = render partial: 'tasks/table_tasks_body', locals: { tasks: @tasks_done }

  table align="right" padding= "10px" class="task_animation kureyon_font waku_image detail_task_font" id="show_task_detail"

div.container

  - if flash[:notice]
    javascript:
        toastr.success('#{flash[:notice]}');