config/routes.rb
Rails.application.routes.draw do

  namespace :api, { format: 'json' }   do
    resources :tasks, only: [:update]
    get 'tasks/calendar' => 'tasks#calendar'
    get 'tasks/mail' => 'tasks#mail'
  end

  root 'tasks#index'
  resources :tasks, except: [:index]
  get '/my_tasks' => 'tasks#index'
  resources :users, except: [:index, :destroy]
  put '/users/done_osekkyo/:id' => 'users#done_osekkyo'
  patch '/users/done_osekkyo/:id' => 'users#done_osekkyo'
  get '/users/:id/check_oko' => 'users#check_oko'
  get '/calendar' => 'tasks#calendar'
  resources :groups, except: [:index, :destroy] do
    resources :tasks, except: [:index] do
      collection do
        get '/' => 'tasks#index_group'
      end
    end
    resources :group_users, only: [:destroy, :show]
  end

  namespace :admin do
    root 'tasks#index'
    resources :tasks, except: [:index]
    get '/calendar' => 'tasks#calendar'
    get '/my_tasks' => 'tasks#index'
    resources :users, :labels
    resources :groups do
      resources :tasks, except: [:index] do
        collection do
          get '/' => 'tasks#index_group'
        end
      end
      resources :group_users, only: [:destroy, :show]
    end
  end

  get 'login', to: 'sessions#new'
  post 'login' => 'sessions#create'
  get 'sessions/destroy'
  get '/ayame' => 'ayame#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_tasks, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :tasks, through: :group_tasks
  has_many :users, through: :group_users
  accepts_nested_attributes_for :group_tasks
  accepts_nested_attributes_for :group_users
  validate :validate_name_error

  def validate_name_error
    if name.empty?
      errors.add(:name, "グループ名を入力してください")
    end
  end
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  layout 'admin_users'
  before_action :admin_user?

  def index
    @group = Group.new
    @groups = Group.all
    @user = current_user
  end

  def update
    @group = find_group_by_id
    @user = current_user
    if @group.update(create_params)
      flash[:notice] = "グループ情報を編集"
    else
      render json: { messages: @group.error.full_messages }, status: :bad_request
    end
  end

  def destroy
    group = find_group_by_id
    group.destroy
    redirect_to admin_groups_path
  end

  private
  def find_group_by_id
    Group.find(params[:id])
  end

  def create_params
    params.require(:group).permit(:id, :name, user_ids: [], task_ids: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  layout "users"

  def new
    @group = Group.new
    @user = current_user
  end

  def create
    group = Group.new(create_params)
    if group.save
      flash[:notice] = "グループを作成しました"
      redirect_to group_tasks_path(group.id)
    else
      render json: { messages: @task.errors.full_messages }, status: :bad_request
    end
  end

  def update
    @group = find_group_by_id
    if @group.update(create_params)
      flash[:notice] = "グループ情報を編集"
      redirect_back(fallback_location: root_path)
    else
      render json: { messages: @group.error.full_messages }, status: :bad_request
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  private
  def find_group_by_id
    Group.find(params[:id])
  end

  def find_user_by_id
    Group.find(params[:user_ids])
  end

  def create_params
    params.require(:group).permit(:id, :name, user_ids: [], task_ids: [])
  end
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/views/admin/groups/_edit_group_modal.html.slim
div class="modal fade black_font" id="edit_button_group#{group.id}" role="dialog"
  div.modal-dialog
    div.modal-content
      div.modal-helper
        button type="button" class="close" data-dismiss="modal"
        h4 class="modal-title huchidori_font" 編集
      div.modal-body
        = render partial: 'form_group', locals: {group: group, submit_text: "更新"}

app/views/admin/groups/_form_group.html.slim
= form_for [:admin, group], html: { class: "data-form" } do |f|
  div.form-group
    = f.label :"グループ名:", class: "control-label huchidori_font"
    = f.text_field :name, class: "form-control"
  / div.form-group
  /   = f.label :"メンバー:", class: "control-label huchidori_font"
  /   = select_tag "group[user_ids]", options_from_collection_for_select(User.all, :id, :name) , class: "searchable", multiple: true, include_blank: true
  div.form-group
    div id="submit_button" class="btn btn-primary data-submit" #{submit_text}

app/views/admin/groups/index.html.slim
div.container.tab-pane
  table class="waku_image_user"
    thead
      tr
        th.text-center 名前
        th.text-center 登録者数
        th.text-center タスク数
        th.text-center colspan="2" 編集
    tbody
      - @groups.each do |group|
        tr
          td.text-center
            = link_to group.name, admin_group_tasks_path(group.id)
          td.text-center = group.users.size
          td.text-center = group.tasks.size
          td.text-center
            div id="edit_button_group" type="button" class="btn glyphicon glyphicon-pencil" data-toggle="modal" data-target="#edit_button_group#{group.id}"
            = render partial: 'edit_group_modal', locals: {group: group}
          td
            = link_to '', admin_group_path(group.id), class: 'btn delete-user-btn glyphicon glyphicon-trash', method: :delete, id:"delete_button", data: { title: t("confirm.title"), confirm: t("confirm.confirm_admin") , cancel: t("confirm.cancel"), commit: t("confirm.commit")}