config/routes.rb
Rails.application.routes.draw do

  namespace :api, { format: 'json' }   do
    resources :tasks, only: [:update]
    get 'tasks/calendar' => 'tasks#calendar'
    get 'tasks/mail' => 'tasks#mail'
  end

  root 'tasks#index'
  resources :tasks, except: [:index]
  get '/my_tasks' => 'tasks#index'
  resources :users, except: [:index, :destroy]
  put '/users/done_osekkyo/:id' => 'users#done_osekkyo'
  patch '/users/done_osekkyo/:id' => 'users#done_osekkyo'
  get '/users/:id/check_oko' => 'users#check_oko'
  get '/calendar' => 'tasks#calendar'
  resources :groups, except: [:index, :destroy] do
    resources :tasks, except: [:index] do
      collection do
        get '/' => 'tasks#index_group'
      end
    end
    resources :group_users, only: [:destroy, :show]
  end

  namespace :admin do
    root 'tasks#index'
    resources :tasks, except: [:index]
    get '/calendar' => 'tasks#calendar'
    get '/my_tasks' => 'tasks#index'
    resources :users, :labels
    resources :groups do
      resources :tasks, except: [:index] do
        collection do
          get '/' => 'tasks#index_group'
        end
      end
      resources :group_users, only: [:destroy, :show]
    end
  end

  get 'login', to: 'sessions#new'
  post 'login' => 'sessions#create'
  get 'sessions/destroy'
  get '/ayame' => 'ayame#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :image
  # mount_uploader :image, UserIconUploader
  has_many :tasks, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users
  has_many :charge_users, class_name: :task, foreign_key: :charge_user_id

  has_secure_password
  validates :name,
    uniqueness: {
      message: "とメールアドレスが同じ組み合わせのユーザが既に存在します。",
      scope: [:email]
  }
  validate :check_empty

  enum admin:{
      admin: true,
      common: false
  }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def check_empty
    # if password.empty?
    #   errors.add(:password, "を入力してください")
    # end
    if email.empty?
      errors.add(:email, "を入力してください")
    end
    if name.empty?
      errors.add(:name, "を入力してください")
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin_users'
  before_action :admin_user?

  def index
    @users = User.all
    @user = current_user
    @group = Group.new
  end


  def destroy
    @user = find_user_by_id
    # pp @user
    if !@user.admin?
      pp @user
      destroy_task
      @user.destroy
      flash[:notice] = "ユーザとタスク削除完了"
      redirect_to admin_users_path
    elsif User.admin.group(:admin).size.values[0] == 1
      flash[:error] = "管理者が０人になるためユーザを削除できません"
      redirect_to admin_users_path
    end
  end

  def edit
    @user = find_user_by_id
  end

  def show
    @user = find_user_by_id
    @group = Group.new
  end


  def update
    @user = find_user_by_id
    if @user.update(create_params)
      flash[:notice] = "ユーザ情報を更新"
    else
      render json: { messages: @user.error.full_messages }, status: :bad_request
    end
  end

  private
  def create_params
    params.require(:user).permit(:id, :name, :email, :password, :password_confirmation, :admin, :image_name)
  end

  def find_user_by_id
    User.find(params[:id])
  end

  def destroy_task
    task = Task.find_by_user_id(find_user_by_id)
    if task.present?
      task.destroy
    end
  end
end

app/controllers/users_controller.rb
require 'kconv'

class UsersController < ApplicationController
  layout "users"
  # skip_before_action :user_logged_in?, only: [new, create]

  def new
    @group = Group.new
    @user = User.new
    render :layout => 'new_user'
  end

  def show
    @user = find_user_by_id
    task = Task.all.where(user_id: current_user.id)
    @tasks_to_do = task.status_to_do
    @tasks_doing = task.status_doing
    @tasks_done = task.status_done
    @group = Group.new
    @groups = Group.all
  end

  def edit
    @group = Group.new
    @user = find_user_by_id
    if session[:user_id] != @user.id
      render partial: 'errors/forbidden'
    end
  end

  def update
    @user = find_user_by_id
    image_name = create_params[:image]
    if image_name.present?
      image = image_name.original_filename
      @user.image_name = image_name.original_filename
      uploadimg(image_name, image)
    end
    if @user.update(create_params)
      pp params[:image]
      flash[:notice] = "ユーザ情報を更新"
      redirect_to my_tasks_path
    else
      render json: { messages: @user.errors.full_messages }, status: :bad_request
    end
  end

  def create
    @user = User.new(create_params)
    if @user.save
      flash[:success] = "新しいユーザを登録しました"
      redirect_to login_path
    else
      render "new"
    end
  end

  def check_oko
    @user = User.find(params[:id])
    # render 'users/check_oko', formats: 'json', handlers: 'jbuilder'
  end

  def done_osekkyo
    user = User.find(params[:id])
    user.oko = false
    user.save
    redirect_to my_tasks_path
  end

  private
  def create_params
    params.require(:user).permit(:id, :name, :email, :password, :password_confirmation, :image)
  end

  def find_user_by_id
    User.find(params[:id])
  end

  def uploadimg(img_object,image_name)
    ext = image_name[image_name.rindex('.') + 1, 4].downcase
    perms = ['.jpg', '.jpeg', '.gif', '.png']
    if !perms.include?(File.extname(image_name).downcase)
      result = 'アップロードできるのは画像ファイルのみです。'
    elsif img_object.size > 4.megabyte
      result = 'ファイルサイズは4MBまでです。'
    else
      path = "public/assets/images/users/#{params[:id]}/"
      FileUtils.mkdir_p(path) unless FileTest.exist?(path)
      File.open(path + "#{image_name.toutf8}", 'wb') { |f| f.write(img_object.read) }
      result = "success"
    end
    return result
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_edit_user_modal.html.slim
div class="modal fade black_font" id="edit_button_user#{user.id}" role="dialog"
  div.modal-dialog
    div.modal-content
      div.modal-helper
        button type="button" class="close" data-dismiss="modal"
        h4 class="modal-title huchidori_font" 編集
      div.modal-body
        = render partial: 'form_user', locals: {user: user, submit_text: "更新"}

app/views/admin/users/_form_user.html.slim
= form_for [:admin, user], html: { class: "data-form" } do |f|
  div.form-group
    = f.label :"名前:", class: "control-label huchidori_font"
    = f.text_field :name, class: "form-control"
  div.form-group
    = f.label :"e-mail:", class: "control-label huchidori_font"
    = f.text_field :email, class: "form-control"
  div.form-group
    = f.label :"権限:", class: "control-label huchidori_font"
    - if user.admin? and User.admin.group(:admin).size.values[0] == 1
      div.red_font
        = f.label :"管理者が一人しかいないため権限を変更できません。"
      = f.select :admin, User.admins.map { |k, _v| [t("role.#{k}"), k] }, {}, class:"form-control", id: "edit_user_status", disabled: true
    - else
      = f.select :admin, User.admins.map { |k, _v| [t("role.#{k}"), k] }, {}, class:"form-control", id:"edit_user_status"
  div.form-group
    div id="submit_button" class="btn btn-primary data-submit" #{submit_text}

app/views/admin/users/index.html.slim
div.container.tab-pane
  table class="waku_image_user"
    thead
      tr
        th.text-center 名前
        th.text-center e-mail
        th.text-center 権限
        th.text-center 登録日
        th.text-center タスク数
        th.text-center colspan="2" 編集
    tbody
      - @users.each do |user|
        tr
          td.text-center = user.name
          td.text-center = user.email
          td.text-center = t("role.#{user.admin}")
          td.text-center = user.created_at.to_s(:published_on)
          td.text-center = user.tasks.size
          td.text-center
            div id="edit_button_user" type="button" class="btn glyphicon glyphicon-pencil" data-toggle="modal" data-target="#edit_button_user#{user.id}"
            = render partial: 'edit_user_modal', locals: {user: user}
          td
            = link_to '', admin_user_path(user.id), class: 'btn delete-user-btn glyphicon glyphicon-trash' ,method: :delete, id: "delete_button", data: { title: t("confirm.title"), confirm: t("confirm.confirm_admin") , cancel: t("confirm.cancel"), commit: t("confirm.commit")}