config/routes.rb
Rails.application.routes.draw do

  namespace :api, { format: 'json' }   do
    resources :tasks, only: [:update]
    get 'tasks/calendar' => 'tasks#calendar'
    get 'tasks/mail' => 'tasks#mail'
  end

  root 'tasks#index'
  resources :tasks, except: [:index]
  get '/my_tasks' => 'tasks#index'
  resources :users, except: [:index, :destroy]
  put '/users/done_osekkyo/:id' => 'users#done_osekkyo'
  patch '/users/done_osekkyo/:id' => 'users#done_osekkyo'
  get '/users/:id/check_oko' => 'users#check_oko'
  get '/calendar' => 'tasks#calendar'
  resources :groups, except: [:index, :destroy] do
    resources :tasks, except: [:index] do
      collection do
        get '/' => 'tasks#index_group'
      end
    end
    resources :group_users, only: [:destroy, :show]
  end

  namespace :admin do
    root 'tasks#index'
    resources :tasks, except: [:index]
    get '/calendar' => 'tasks#calendar'
    get '/my_tasks' => 'tasks#index'
    resources :users, :labels
    resources :groups do
      resources :tasks, except: [:index] do
        collection do
          get '/' => 'tasks#index_group'
        end
      end
      resources :group_users, only: [:destroy, :show]
    end
  end

  get 'login', to: 'sessions#new'
  post 'login' => 'sessions#create'
  get 'sessions/destroy'
  get '/ayame' => 'ayame#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_tasks, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :tasks, through: :group_tasks
  has_many :users, through: :group_users
  accepts_nested_attributes_for :group_tasks
  accepts_nested_attributes_for :group_users
  validate :validate_name_error

  def validate_name_error
    if name.empty?
      errors.add(:name, "グループ名を入力してください")
    end
  end
end

app/views/layouts/_ayame.html.slim
.ayame id="ayame"
  .arrow_box.arrow_box_temp
    .hukidashi_text
      .notice_text
        label id="notice_text_label"
      - if controller.action_name != "calendar"
        .form-serch-task
          label なんでも検索してやるぞ！
          input.center-block type="text" size="25" maxlength="15" id="search-text" placeholder="入力するのじゃ！"
          div
            label
              input type="radio" name="searchTasks" value="caption" checked="checked" タスク
            label
              input type="radio" name="searchTasks" value="chargeUser" 担当者
            label
              input type="radio" name="searchTasks" value="user" 作成者
            label
              input type="radio" name="searchTasks" value="label" ラベル
          div.serch-result
            div.search-result__hit-num
            div.search-result__list
      - else
        .form-calendar
          label ここではまだ完了していないタスクをみることができるぞ！
  .ayame_image id="ayame_image_temp"
    img width="300%" id="ayame_image" src="/assets/images/system/sd_ayame_nomal.png"

app/views/layouts/_form_group_new.html.slim
div class="modal fade" id="new_group_modal" role="dialog"
  div.modal-dialog
    div.modal-content
      div.modal-header
        button type="button" class="close" data-dismiss="modal"
        h4 class="modal-title" グループを追加
      div.modal-body
        = form_for [group] do |f|
          div.form-group
            = label_tag "グループ名: "
            = text_field_tag "group[name]", params[:name], class: "form-control"
          div.form-group
            = label_tag "メンバー:　 "
            = select_tag "group[user_ids]", options_from_collection_for_select(User.all, :id, :name, { selected: User.find(session[:user_id]).id })  , class: "select2", multiple: true, include_blank: true
          / = f.collection_select :user_id, class: "form-control"
          div.form-group
            = f.submit "グループを追加"

app/views/layouts/_header.html.slim
title
  | お仕事管理♡
= favicon_link_tag 'sd_ayame.png'
= csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
/ script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js"
/ script src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"
script src="https://code.createjs.com/1.0.0/preloadjs.min.js"
script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"
script src="https://unpkg.com/axios/dist/axios.min.js"

- if controller.controller_name != "user" and controller.action_name != "new"
  = render partial: 'layouts/form_group_new', locals: {group: @group}

app/views/layouts/_navbar_my_name.html.slim
ul.navbar-nav.navbar-right
  a.navbar-brand.dropdown-toggle data-toggle="dropdown"
    - if @user.image_name == "default_user.png"
      img.user_icon4 height="40px" src = "/assets/images/users/#{@user.image_name}"
    - else
      img.user_icon4 height="40px" src = "/assets/images/users/#{@user.id}/#{@user.image_name}"
  span class="create"
  ul.dropdown-menu.right role="menu"
    - if @user.admin?
      li = link_to t("description.admin"), admin_root_path
      li = link_to t("description.common"), root_path
    - if @user.id != nil
      li = link_to "プロフィール", edit_user_path(@user.id)
    li.divider
    li = link_to t("description.logout"), sessions_destroy_path

app/views/layouts/_navbar_title.html.slim
div.navbar-header
  ul.navbar-nav.title-nav
    a.navbar-brand.dropdown-toggle data-toggle="dropdown"
      = t("description.title")
    ul.dropdown-menu.left
      - @user.groups.each do |group|
        - if params[:controller].to_s == "admin/tasks" or params[:controller].to_s == "admin/groups" or params[:controller].to_s == "admin/labels" or params[:controller].to_s == "admin/users"
          li.text-center = link_to group.name, admin_group_tasks_path(group.id)
        - else
          li.text-center = link_to group.name, group_tasks_path(group.id)
      li.divider
      li.text-center
        div id="new_group" data-toggle="modal" data-target="#new_group_modal"
          label グループを作成

app/views/layouts/_taster.html.slim
- if flash.present?
  -flash.each do |type, message|
    javascript:
      toastr["#{type}"]("#{message}");

app/views/layouts/admin_tasks.html.slim
doctype html
html
  head
    = render 'layouts/header'
  body.background_color.body_style
    nav class="navbar header_color_admin navbar-default"
      div.container
        = render partial: 'layouts/navbar_title'
        div class="collapse navbar-collapse" id="navbarIndex"
          = render partial: 'layouts/navbar_my_name'
          ul class="nav nav-justified customNav"
            li = link_to t("description.index_groups"), admin_groups_path
            li = link_to t("description.index_users"), admin_users_path
            li = link_to t("description.index_labels"), admin_labels_path
            li = link_to t("description.index_tasks"), admin_my_tasks_path
            li = link_to "カレンダー", admin_calendar_path


      div class="modal fade" id="serch_task" role="dialog"
        div.modal-dialog
          div.modal-content
            div.modal-header
              button type="button" class="close" data-dismiss="modal"
              h4 class="modal-title" 検索
            div.modal-body
              / = render partial: 'form_task', locals: {task: @task, submit_text: t("task.add")}
              = render partial: 'form_serch'
    = render partial: 'layouts/ayame'
    = render 'layouts/taster'
    = yield

app/views/layouts/admin_users.html.slim
doctype html
html
  head
    = render 'layouts/header'
  body.background_color
    nav class="navbar header_color_admin navbar-default"
      div.container
        = render partial: 'layouts/navbar_title'
        div class="collapse navbar-collapse" id="navbarIndex"
          = render partial: 'layouts/navbar_my_name'
          ul class="nav nav-justified customNav"
            li = link_to t("description.index_groups"), admin_groups_path
            li = link_to t("description.index_users"), admin_users_path
            li = link_to t("description.index_labels"), admin_labels_path
            li = link_to t("description.index_tasks"), admin_my_tasks_path
            li = link_to "カレンダー", admin_calendar_path

    = render 'layouts/taster'
    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | お仕事管理♡
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/taster'
    = yield

app/views/layouts/new_user.html.slim
doctype html
html
  head
    = render 'layouts/header'
  body.background_color
    = render 'layouts/taster'
    = yield

app/views/layouts/tasks.html.slim
doctype html
html
  head
    = render 'layouts/header'
  body.background_color.body_style
    nav class="navbar header_color navbar-default"
      div.container
        = render partial: 'layouts/navbar_title'
        div class="collapse navbar-collapse" id="navbarIndex"
          = render partial: 'layouts/navbar_my_name'
          ul class="nav nav-justified customNav"
            li = link_to t("description.index_tasks"), my_tasks_path
            li = link_to "カレンダー", calendar_path


      div class="modal fade" id="serch_task" role="dialog"
        div.modal-dialog
          div.modal-content
            div.modal-header
              button type="button" class="close" data-dismiss="modal"
              h4 class="modal-title" 検索
            div.modal-body
              = render partial: 'form_serch'

    = render partial: 'layouts/ayame'

    = render 'layouts/taster'
    = yield

app/views/layouts/users.html.slim
doctype html
html
  head
    = render 'layouts/header'
  body.background_color
    nav class="navbar header_color navbar-default"
      div.container
        = render partial: 'layouts/navbar_title'
        div class="collapse navbar-collapse" id="navbarIndex"
          = render partial: 'layouts/navbar_my_name'
          ul class="nav nav-justified customNav"
            li = link_to t("description.index_tasks"), my_tasks_path

    = render 'layouts/taster'
    = yield